#http.listener.host=localhost
#http.listener.port=8081
#mysql.host=localhost
#mysql.port=3306
#mysql.user=root
#mysql.database=test

http:
 listener:
  host: "localhost"
  port: "8081"
mysql:
 host: "localhost"
 port: "3306"
 user: "root"
 database: "test" 
  
      